<a href="https://colab.research.google.com/github/mygoal-javadeveloper/Qwings-Interview-Tasks/blob/main/QWings2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Name: Nisrin Dhoondia

## GitHub: https://github.com/mygoal-javadeveloper

## Kaggle: https://www.kaggle.com/nisrindhoondia

## My Portfolio (Github and others): https://linktr.ee/nisrindhoondia

# Q. 3- If x=[1,2,3,4,5,6,7,8,9,10] and y=[5,10,15,20,25,30,35,40,45,50], write a python program to find the mean squared error if linear regression model is used to plot the trendline

## Case-1: Solve the above problem using inbuilt function

## Case-2: Solve the above problem without using any inbuilt function

In [1]:
x=[1,2,3,4,5,6,7,8,9,10]
y=[5,10,15,20,25,30,35,40,45,50]

# Case-1: Solve the above problem using train_test_split inbuilt function

In [2]:
from sklearn.model_selection import train_test_split 
import numpy as np

In [3]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state= 47)

In [4]:
X_train, y_train, X_test, y_test  

([5, 6, 4, 9, 1, 10, 7, 8], [25, 30, 20, 45, 5, 50, 35, 40], [3, 2], [15, 10])

In [5]:
X_train = np.array(X_train, dtype=np.float64).reshape((-1, 1))
X_train

array([[ 5.],
       [ 6.],
       [ 4.],
       [ 9.],
       [ 1.],
       [10.],
       [ 7.],
       [ 8.]])

In [6]:
X_train.shape

(8, 1)

In [7]:
y_train = np.array(y_train, dtype=np.float64)
y_train

array([25., 30., 20., 45.,  5., 50., 35., 40.])

In [8]:
X_test = np.array(X_test, dtype=np.float64).reshape((-1, 1))
X_test

array([[3.],
       [2.]])

In [9]:
y_test = np.array(y_test, dtype=np.float64)
y_test

array([15., 10.])

In [10]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
pred = model.predict(X_test)

In [12]:
pred

array([15., 10.])

In [13]:
from sklearn.metrics import mean_squared_error
print('MSE:')
print(mean_squared_error(y_test, pred))

MSE:
0.0


# Case-2: Solve the above problem without using any inbuilt function

In [14]:
sum = 0 
for i in range(len(y_test)):
  squareddiff = ((y_test[i] - pred[i]) ** 2)
  sum = sum + squareddiff
mse_cal = sum / len(y_test)
print('MSE:')
print(mse_cal)

MSE:
0.0
